PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  joining_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  email TEXT,
  password TEXT
);

CREATE TABLE IF NOT EXISTS payment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  payer_user_id INTEGER NOT NULL,
  amount REAL NOT NULL,
  time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  status TEXT CHECK(status IN ('settled', 'unsettled')) NOT NULL,
  FOREIGN KEY (payer_user_id) REFERENCES user(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);